import type { Metadata } from "next";
import { Button, themeClass } from "@repo/ui";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className={themeClass}>
      <body>
        {children}
        <Button />
      </body>
    </html>
  );
}
