import "@repo/theme/css";
import { Spinner, Text } from "@repo/ui/components";
import type { Metadata } from "next";
import { Suspense } from "react";
import * as css from "./layout.css";
import "./reset.css";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" style={{ fontSize: "0.875rem" }}>
      <Text asChild>
        <body className={css.body}>
          <Suspense fallback={<PageLoader />}>{children}</Suspense>
        </body>
      </Text>
    </html>
  );
}

function PageLoader() {
  return (
    <div className={css.pageSuspense}>
      <Spinner size={"2em"} />
    </div>
  );
}
